import type { ProjectAnalysisReport } from "@breakguard/core-types";

export const SAMPLE_ENTERPRISE_REPORT: ProjectAnalysisReport = {
  timestamp: new Date().toISOString(),
  projectMetadata: {
    name: "cloudscale-saas-dashboard",
    version: "2.4.0",
    path: "/home/projects/cloudscale-saas",
    lockfileType: "pnpm",
  },
  summary: {
    totalDependencies: 34,
    directCount: 8,
    transitiveCount: 26,
    scannedFiles: 42,
    averageRiskScore: 68,
    safeCount: 2,
    moderateCount: 2,
    breakingWarningCount: 4,
    deprecatedCount: 1,
    vulnerableCount: 2,
    ghostDependenciesCount: 1,
    unusedDependenciesCount: 1,
  },
  ghostDependencies: ["clsx"],
  unusedDependencies: ["chalk"],
  dependencies: {
    axios: {
      id: "axios@0.27.2",
      name: "axios",
      version: "0.27.2",
      latestVersion: "1.7.9",
      requestedRange: "^0.27.2",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: { "follow-redirects": "1.15.4" },
      astUsage: {
        packageName: "axios",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 14,
        totalCallSites: 38,
        importedSymbols: ["default", "get", "post", "create", "AxiosError"],
        files: [
          {
            filePath: "src/api/client.ts",
            relativePath: "src/api/client.ts",
            totalCallCount: 6,
            imports: [
              { type: "default", importedName: "default", localName: "axios", line: 2, column: 1 },
              { type: "named", importedName: "AxiosError", localName: "AxiosError", line: 3, column: 1 },
            ],
            calls: [
              { methodName: "create", line: 12, column: 22, argumentsCount: 1 },
              { methodName: "interceptors.request.use", line: 18, column: 3 },
              { methodName: "interceptors.response.use", line: 24, column: 3 },
            ],
          },
          {
            filePath: "src/services/billing.ts",
            relativePath: "src/services/billing.ts",
            totalCallCount: 8,
            imports: [{ type: "default", importedName: "default", localName: "axios", line: 1, column: 1 }],
            calls: [
              { methodName: "post", line: 45, column: 18, argumentsCount: 2 },
              { methodName: "get", line: 72, column: 18, argumentsCount: 1 },
              { methodName: "delete", line: 98, column: 18, argumentsCount: 1 },
            ],
          },
          {
            filePath: "src/services/auth.ts",
            relativePath: "src/services/auth.ts",
            totalCallCount: 12,
            imports: [{ type: "default", importedName: "default", localName: "axios", line: 4, column: 1 }],
            calls: [
              { methodName: "post", line: 34, column: 22 },
              { methodName: "get", line: 60, column: 22 },
            ],
          },
        ],
      },
      vulnerabilities: [
        {
          id: "GHSA-8hc4-vh64-cxmj",
          summary: "Axios SSRF & Header injection vulnerability in follow-redirects chain",
          severity: "HIGH",
          affectedRange: "<= 0.27.2",
          fixedIn: "1.6.0",
          references: ["https://nvd.nist.gov/vuln/detail/CVE-2023-45857"],
        },
      ],
      risk: {
        score: 88,
        level: "CRITICAL",
        breakdown: {
          semverJump: "major",
          semverScore: 42,
          usageDensityScore: 35,
          deprecationScore: 0,
          vulnerabilityScore: 20,
          penaltyNotes: [
            "Major SemVer jump (0.27.2 ➔ 1.7.9) introduces breaking changes in AxiosHeaders, error serialization, and proxy config.",
            "High call density: Package used across 14 files with 38 invocations.",
            "Known HIGH severity vulnerability present in current version.",
          ],
        },
        summary: "Critical breaking risk: Axios v0.x -> v1.x overhaul affects header handling and interceptors.",
        recommendedAction: "Migrate AxiosHeaders syntax in src/api/client.ts, verify interceptor return types, and test mock adapters.",
        changelogNotice: "Axios 1.0.0 completely rewrote headers handling and removed automatic stringification of FormData in Node.",
      },
    },

    request: {
      id: "request@2.88.2",
      name: "request",
      version: "2.88.2",
      latestVersion: "2.88.2",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: { "tough-cookie": "2.5.0", qs: "6.5.3" },
      isDeprecated: true,
      deprecationReason: "request has been deprecated, see https://github.com/request/request/issues/3142",
      astUsage: {
        packageName: "request",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 3,
        totalCallSites: 7,
        importedSymbols: ["default"],
        files: [
          {
            filePath: "src/legacy/webhook-dispatcher.ts",
            relativePath: "src/legacy/webhook-dispatcher.ts",
            totalCallCount: 7,
            imports: [{ type: "default", importedName: "default", localName: "request", line: 1, column: 1 }],
            calls: [
              { methodName: "post", line: 28, column: 5 },
              { methodName: "get", line: 55, column: 5 },
            ],
          },
        ],
      },
      vulnerabilities: [
        {
          id: "GHSA-p8p7-x Yoda-xxxx",
          summary: "Server-Side Request Forgery via bypass in deprecated request library",
          severity: "HIGH",
          affectedRange: "<= 2.88.2",
          references: ["https://github.com/request/request/issues/3142"],
        },
      ],
      risk: {
        score: 92,
        level: "CRITICAL",
        breakdown: {
          semverJump: "none",
          semverScore: 0,
          usageDensityScore: 15,
          deprecationScore: 25,
          vulnerabilityScore: 20,
          penaltyNotes: [
            "Package is completely DEPRECATED and abandoned by upstream maintainers.",
            "Security vulnerability exists without official patch available.",
            "Used in critical webhook dispatch path (src/legacy/webhook-dispatcher.ts).",
          ],
        },
        summary: "Package is abandoned and insecure. Must be replaced.",
        recommendedAction: "Replace 'request' with native fetch or 'undici' / 'ky'.",
        changelogNotice: "Project archived on GitHub Feb 11, 2020.",
      },
    },

    "@tanstack/react-query": {
      id: "@tanstack/react-query@4.36.1",
      name: "@tanstack/react-query",
      version: "4.36.1",
      latestVersion: "5.66.0",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: {},
      astUsage: {
        packageName: "@tanstack/react-query",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 22,
        totalCallSites: 64,
        importedSymbols: ["useQuery", "useMutation", "useQueryClient", "QueryClient"],
        files: [
          {
            filePath: "src/hooks/useUsers.ts",
            relativePath: "src/hooks/useUsers.ts",
            totalCallCount: 4,
            imports: [{ type: "named", importedName: "useQuery", localName: "useQuery", line: 1, column: 1 }],
            calls: [{ methodName: "useQuery", line: 15, column: 10, argumentsCount: 2 }],
          },
          {
            filePath: "src/hooks/useCheckout.ts",
            relativePath: "src/hooks/useCheckout.ts",
            totalCallCount: 6,
            imports: [{ type: "named", importedName: "useMutation", localName: "useMutation", line: 2, column: 1 }],
            calls: [{ methodName: "useMutation", line: 32, column: 10 }],
          },
        ],
      },
      risk: {
        score: 82,
        level: "BREAKING_WARNING",
        breakdown: {
          semverJump: "major",
          semverScore: 42,
          usageDensityScore: 35,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: [
            "Major SemVer jump (4.36.1 ➔ 5.66.0) removes overloaded useQuery syntax.",
            "In v5, useQuery accepts a single object parameter { queryKey, queryFn } rather than positional arguments.",
            "High call density: 64 invocations across 22 components/hooks.",
          ],
        },
        summary: "Major breaking changes in hook signatures. Codemod required.",
        recommendedAction: "Run '@tanstack/react-query/codemod' to convert positional useQuery calls to single-object syntax.",
        changelogNotice: "TanStack Query v5 unified all hooks to single-object arguments and renamed callbacks.",
      },
    },

    "date-fns": {
      id: "date-fns@2.30.0",
      name: "date-fns",
      version: "2.30.0",
      latestVersion: "4.1.0",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: {},
      astUsage: {
        packageName: "date-fns",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 8,
        totalCallSites: 18,
        importedSymbols: ["format", "parseISO", "differenceInDays"],
        files: [
          {
            filePath: "src/utils/date.ts",
            relativePath: "src/utils/date.ts",
            totalCallCount: 5,
            imports: [{ type: "named", importedName: "format", localName: "format", line: 1, column: 1 }],
            calls: [{ methodName: "format", line: 14, column: 10 }],
          },
        ],
      },
      risk: {
        score: 75,
        level: "BREAKING_WARNING",
        breakdown: {
          semverJump: "major",
          semverScore: 44,
          usageDensityScore: 25,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: [
            "Major version jump (2.30.0 ➔ 4.1.0) changed argument types, timezone handling, and removed sub-path imports.",
          ],
        },
        summary: "Breaking changes in date formatting tokens and locale imports.",
        recommendedAction: "Review date formatting strings and update locale import statements to date-fns/locale.",
      },
    },

    lodash: {
      id: "lodash@4.17.21",
      name: "lodash",
      version: "4.17.21",
      latestVersion: "4.17.21",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: {},
      astUsage: {
        packageName: "lodash",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 16,
        totalCallSites: 42,
        importedSymbols: ["debounce", "cloneDeep", "merge", "get"],
        files: [
          {
            filePath: "src/components/SearchInput.tsx",
            relativePath: "src/components/SearchInput.tsx",
            totalCallCount: 3,
            imports: [{ type: "named", importedName: "debounce", localName: "debounce", line: 1, column: 1 }],
            calls: [{ methodName: "debounce", line: 20, column: 12 }],
          },
        ],
      },
      risk: {
        score: 18,
        level: "SAFE",
        breakdown: {
          semverJump: "none",
          semverScore: 0,
          usageDensityScore: 10,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: ["Package is up to date on latest release."],
        },
        summary: "Already on latest stable version.",
        recommendedAction: "No action needed.",
      },
    },

    react: {
      id: "react@18.2.0",
      name: "react",
      version: "18.2.0",
      latestVersion: "19.0.0",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: {},
      astUsage: {
        packageName: "react",
        isUsed: true,
        isGhostDependency: false,
        isUnusedDependency: false,
        totalFilesCount: 38,
        totalCallSites: 110,
        importedSymbols: ["useState", "useEffect", "useMemo", "useCallback", "createContext"],
        files: [],
      },
      risk: {
        score: 65,
        level: "MODERATE",
        breakdown: {
          semverJump: "major",
          semverScore: 40,
          usageDensityScore: 25,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: [
            "React 19 removes legacy Context API, defaultProps on function components, and modifies ref handling.",
          ],
        },
        summary: "React 18 to 19 migration requires peer dependency alignment.",
        recommendedAction: "Check third-party UI library support before upgrading React and React-DOM.",
      },
    },

    "react-dom": {
      id: "react-dom@18.2.0",
      name: "react-dom",
      version: "18.2.0",
      latestVersion: "19.0.0",
      category: "dependencies",
      isTransitive: false,
      depth: 1,
      parents: ["react"],
      dependencies: {},
      risk: {
        score: 60,
        level: "MODERATE",
        breakdown: {
          semverJump: "major",
          semverScore: 40,
          usageDensityScore: 15,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: ["React DOM v19 deprecates ReactDOM.render in favor of createRoot."],
        },
        summary: "Pair with React upgrade.",
        recommendedAction: "Upgrade alongside react.",
      },
    },

    chalk: {
      id: "chalk@4.1.2",
      name: "chalk",
      version: "4.1.2",
      latestVersion: "5.4.1",
      category: "devDependencies",
      isTransitive: false,
      depth: 1,
      parents: [],
      dependencies: {},
      astUsage: {
        packageName: "chalk",
        isUsed: false,
        isGhostDependency: false,
        isUnusedDependency: true,
        totalFilesCount: 0,
        totalCallSites: 0,
        importedSymbols: [],
        files: [],
      },
      risk: {
        score: 10,
        level: "SAFE",
        breakdown: {
          semverJump: "major",
          semverScore: 10,
          usageDensityScore: 0,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: ["Package is never imported anywhere in codebase (Unused Dependency)."],
        },
        summary: "Unused package detected. Safe to remove or update.",
        recommendedAction: "Remove 'chalk' from package.json dependencies to reduce bundle and install footprint.",
      },
    },

    // Transitive dependencies
    "follow-redirects": {
      id: "follow-redirects@1.15.4",
      name: "follow-redirects",
      version: "1.15.4",
      latestVersion: "1.15.6",
      category: "transitive",
      isTransitive: true,
      depth: 2,
      parents: ["axios"],
      dependencies: {},
      risk: {
        score: 15,
        level: "SAFE",
        breakdown: {
          semverJump: "patch",
          semverScore: 5,
          usageDensityScore: 0,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: [],
        },
        summary: "Transitive dependency required by axios.",
        recommendedAction: "Will be updated automatically when upgrading parent package.",
      },
    },

    "tough-cookie": {
      id: "tough-cookie@2.5.0",
      name: "tough-cookie",
      version: "2.5.0",
      latestVersion: "4.1.4",
      category: "transitive",
      isTransitive: true,
      depth: 2,
      parents: ["request"],
      dependencies: {},
      risk: {
        score: 45,
        level: "MODERATE",
        breakdown: {
          semverJump: "major",
          semverScore: 40,
          usageDensityScore: 0,
          deprecationScore: 0,
          vulnerabilityScore: 0,
          penaltyNotes: [],
        },
        summary: "Transitive dependency required by request.",
        recommendedAction: "Eliminate by removing parent 'request' package.",
      },
    },
  },
};
